server:
  port: 3000

spring:
  application:
    name: backend

  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  sql:
    init:
      platform: postgresql
      mode: always

  output:
    ansi:
      enabled: always

  config:
    import: optional:file:.env[.properties]

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR

debug: true
