server:
  port: 3000

spring:
  application:
    name: backend

  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

  sql:
    init:
      platform: postgresql
      mode: never

  output:
    ansi:
      enabled: always

  config:
    import: optional:secret.yml

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR

debug: true
