server:
  port: 3000

spring:
  application:
    name: backend

  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: ${DB_URL}

  output:
    ansi:
      enabled: always

  sql:
    init:
      mode: always

  config:
    import: optional:file:.env[.properties]

logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR

debug: true
